sqlite_db: 'books.db'
postgres:
  host: 'localhost'
  dbname: 'books'
  user: 'postgres'
  password: '1402'
rabbitmq:
  host: 'localhost'
  queue: 'books'
sockets:
  host: '176.109.109.31'
  port: 65432
encryption:
  method: 'aes_rsa'
  public_key_path: 'public.pem'
  private_key_path: 'private.pem'